### PR TITLE
use the otherFlags parameter.

### PR DESCRIPTION
**Pull request by matthid**
This is what #305 broke. Actually we probably should even remove that parameter now. If there is a problem to workaround we should probably add it to FSharp.Scripting...

For now that would be a breaking change, but maybe something to note for a major update. Is it possible to obsolete this optional parameter?

### CODE REVIEW

**Comment by forki** [comment]
whatever helps to get it working again.

**Comment by matthid** [comment]
@forki Do you mix this with the fake issue? Or did this actually hit you (I though no-one is actually using that "otherFlags" parameter besides me)? If this hit you I would be interested for what you use that parameter...

**Comment by forki** [comment]
woah. sorry. Yep I mixed it. shame on me ;-)

**Comment by tpetricek** [comment]
Released in v2.9.4.

**Pull request merged**
