### PR TITLE
Enabled and fixed 3 CommonMark test sections

### PR DESCRIPTION
**Pull request by theprash**
I enabled "Paragraphs", "Precedence" and "Tabs" and fixed some failing tests.

Note that while fixing `(|BlockquoteStart|_|)`, I rewrote it with regex as it seemed much clearer.

### CODE REVIEW

**Comment by tpetricek** [comment]
Sorry for the delay here - this looks amazing!

I guess the one thing that's now different is that `BlockquoteStart` will also match code that is actually inline code (4 spaces followed by `>`). This does not seem to be an issue (we probably look for code before looking for blockquote), but it might be safer to allow only up to 3 spaces in the ` *` part of the regex. Or does the CommonMark spec allow more spaces?

**Comment by theprash** [comment]
There's no harm in limiting it to three leading spaces, so I've made that change. I also added a test for a blockquote with leading spaces.

**Comment by matthid** [comment]
Wow very nice! A good step forward in following the CommonMark spec :+1: 
The changes look good to me :shipit:

**Comment by tpetricek** [comment]
Fantastic! Thank you very much for the awesome PR!

**Comment by theprash** [comment]
You're welcome. Thanks to you both for reviewing and accepting it :smiley:

**Pull request merged**
