### PR TITLE
Improve logging of FSharp.Formatting

### PR DESCRIPTION
**Pull request by matthid**
With this I plan to fix the mentioned lack of logging (in #325).
I removed the shared `Log.fs` files and added a new `FSharp.Formatting.Common` project to have a single point of configuration for logging (from the outside, as otherwise we have multiple classes at runtime, one in each project).

Another nice sideeffect of this patch is that all the Fharp.Formatting libraries will no longer write into the standard output stream by default (When not explicitly configured with a ConsoleTraceListener). 

Finally I changed the type of some messages to no longer appear in the console (The warning when a documentation for a member could not be found). Those can now be found in the `FSharp.Formatting.svclog` file.

We should start a discussion of what logfiles we want to write and which messages should be printed by default. My current configuration (Setup via `FSharp.Formatting.fsx`) is like this:
- Console: >= Information (Just the message)
- Svclog: ALL (+ALL) -> Will become quite big (several MB), but contains every bit of information
- Logfile: >= Warning (+DateTime)
And all files will be deleted on startup (so only the logfile of the last run is available).
Now thinking about it, the warning-only logfile is probably not that useful.

IMHO this is a nice way to cleanup the output a bit and at the same time have a way to improve debugging.

_TODOs:_
- [x] Switch FSharp.Formatting to `TraceSource`
- [x] Switch Yaaf.FSharp.Scripting to `TraceSource` 
- [x] Add Logging as suggested by #325 (should simplify debugging of #328 as well)

Edit:
It seems like mono doesn't support filtering on TraceSources, this means on mono all messages will be printed to the console, that's a bit unfortunate but not a real problem IMHO.
http://lists.ximian.com/pipermail/mono-list/2012-November/049106.html
http://stackoverflow.com/questions/22590799/mono-tracesource-switch-behaviour

### CODE REVIEW

**Comment by matthid** [comment]
@dsyme Regarding your [comment](https://github.com/tpetricek/FSharp.Formatting/issues/325#issuecomment-120325573)

> It uses a secondary in-process F# interactive instance to evaluate stuff during documentation generation, in the context of an existing fsi.exe F# interactive execution of the generate.fsx script. There's definitely potential for problems or gremlins here.

It's actually not that bad, because we can access the complete "fsi.exe" output, so when something fails this output tells us exactly what has happened.

The problem is that we don't have access to the same amount of information via "FSharpChecker". We often have the problem that it works intially, but as soon as we dig into the references (which are the assemblies we want to analyse) it crashes with some internal compiler error nobody is able to decrypt. Is there a trick to access something like the "fsi" stdout?

>  it would be very helpful if FSharp.Formatting printed out the exact command line option set being passed to create the FSharpChecker and also to FsiEvaluationSession.

All this information is now available with this path in a logfile called "FSharp.Formatting.svclog"
 - FSharpChecker: Watch out for entries called "Checker Arguments: "
 - FsiEvaluationSession: Watch out for entries called "Starting nested fsi.exe with args: "

**Comment by tpetricek** [comment]
Very nice work, thank you @matthid! This is going to be super useful for the future of the project (I added logging to R provider and it really helped tremendously debugging things!)

I was a bit worried about adding another `dll`, but looking at your changes - I agree that this was the right thing to do here. I'm just releasing a new version with this, so we'll see what happens when people start using it :-). Hopefully they reference it using the `fsx` file these days!

**Comment by matthid** [comment]
> Hopefully they reference it using the fsx file these days!

Exactly, I couldn't figure out a good way to set the defaults from within the code (without rendering app.config unusable).

Another note is that the logfile is really only useful when opened on windows :). I don't know how good the XmlTraceListener is on the latest mono versions, but in the past I used my own implementation to get a proper logfile on mono (https://github.com/matthid/Yaaf.Logging/blob/develop/src/source/Yaaf.Logging/SimpleXmlWriterTraceListener.fs#L56). So, if we get unusable logfiles we can either switch to raw text or use my implementation.

**Comment by tpetricek** [comment]
Sounds good! In any case, getting a good log in 50% of cases is better than in 0% of cases :-)

**Pull request merged**
