### PR TITLE
Fix some broken links in documentation

### PR DESCRIPTION
**Pull request by bjartwolf**
Missed a /misc/ in path, have not fixed all broken links as I haven't found all files yet.

### CODE REVIEW

**Comment by tpetricek** [comment]
Thanks!

Which other links remain broken?

**Comment by bjartwolf** [comment]
https://github.com/tpetricek/FSharp.Formatting/blob/master/literate/content/style.css
https://github.com/tpetricek/FSharp.Formatting/blob/master/literate/content/tips.js

**Comment by bjartwolf** [comment]
I found them, I was just being lazy the first time and used the search in GitHub, and I couldn't see them in there so assumed they were gone...

**Comment by tpetricek** [comment]
Great, thanks for fixing the remaining issues!

**Pull request merged**
