### PR TITLE
[wip] support for all recommended xml tags

### PR DESCRIPTION
**Pull request by ademar**
The purpose of this PR is to bring support for all recommended tags (ref #295)

https://msdn.microsoft.com/en-us/library/vstudio/5ast78ax(v=vs.100).aspx

TODO: unit tests

### CODE REVIEW

**Comment by tpetricek** [comment]
Very cool, it will be great to have this!

**Comment by matthid** [comment]
Yeah I think this is very useful, thanks! Can you rebase your changes against the latest changes (ideally against the `fix_extension_methods` branch)?

**Comment by ademar** [comment]
Guys, I have rebased this PR against master.

I have disabled this test https://github.com/tpetricek/FSharp.Formatting/commit/4f4c3c288f01abc97eedb4976bd5a8cf6e5b8b37

In our use case, `markDownComments = false`, we want to render all comments regardless of whether or not they are enclosed by XML tags.

It would be nice if this gets merged, I could use it over here https://github.com/SuaveIO/suave/pull/239

**Comment by matthid** [comment]
There are multiple reasons why I think we should support special commands, even when `markDownComments = false`:

- It should be as simple as for the markdown case to exclude some comments from the website (while still having them in the IDE).
- Problem is that sometimes `FSharp.Compiler.Service` throws errors on some language constructs, and `[omit]` is an easy workaround for such cases.

So it was definitely "by-design" that I called https://github.com/tpetricek/FSharp.Formatting/pull/331/files#diff-e2212151e1f9b6e7e085820d2a6b71caL652 (`findCommands`) in both cases.

**Comment by matthid** [comment]
@tpetricek What do you think?

The discussion is about using 

```
/// [omit]
```

in case of `markDownComments = false`, where we ignore other markdown constructs.

**Comment by ademar** [comment]
@matthid Sorry, I now realize I did not understood correctly the purpose of `findCommand` and `[omit]`. Let me correct that.

**Pull request merged**
