### PR TITLE
Even more global caching, now even with different layout-roots.

### PR DESCRIPTION
**Pull request by matthid**
This is part of what was discussed in #274, after seeing how the layout-roots parameter is used for different localization. 

Now there is no more reason against using the layout-roots parameter for this (as long as you do not specify the same template via full-path as ProjectScaffold is doing it).

### CODE REVIEW

**Comment by tpetricek** [comment]
Hmm, are you saying that this is better way of doing things, but it will break most ProjectScaffold-based projects if they update to newer version of F# Formatting?

(That would be very unfortunate! Or am I misunderstanding something?)

**Comment by matthid** [comment]
This PR should be harmless. But you are correct for my other PR (with the additional commit).
It should only break for people who have forked since the bug was introduced (and only their localization will be hit, everything will be english until they fix the bug). The only alternative I see is to live with the bug.

**Comment by tpetricek** [comment]
Oh, this only affects localizations... now I finally understand this (thanks for making that clear)! 

Then we should be good - I think only F# Compiler Service and F# Data have translations, so I think we just need to fix:

 - https://github.com/fsharp/FSharp.Data/blob/master/docs/tools/generate.fsx
 - https://github.com/fsharp/FSharp.Compiler.Service/blob/master/docs/tools/generate.ja.fsx
 - https://github.com/fsharp/FSharp.Compiler.Service/blob/master/docs/tools/generate.fsx

Is that correct?

**Comment by matthid** [comment]
Uh, Ok I looked into this again (especially since those projects had their localization long before I introduced the bug) and I think I got the impact wrong.
I now think no project is hit by that because ProjectScaffold uses a forward template `docpage.cshtml` and it doesn't really matter if it is localized or not, because it only forwards to `template.cshtml` which will in turn be localized correctly... So https://github.com/fsprojects/ProjectScaffold/pull/155 wasn't strictly required (but it's still a good change to make IMHO).

This change (#281 to be exact) only hits people relying on the bug, which appeared in Sep 2014. Everything what worked before that date should still work after applying this (or work again if it broke).

(Sorry for the confusion)

**Comment by tpetricek** [comment]
Oh, right - thanks for digging deeper! 

I'll release a new version with the changes then. And I agree that the change in ProjectScaffold is a good one anyway.

**Pull request merged**
