### PR TITLE
Update to latest FSharp.Compiler.Service

### PR DESCRIPTION
**Pull request by forki**
/cc @tpetricek @dungpa 

I don't understand the IsGetterMethod => IsPropertyGetterMethod change. Had to revert this. Any ideas?

### CODE REVIEW

**Comment by dungpa** [comment]
It's really confusing but I think you can replace `mem.IsGetterMethod` by `mem.IsPropertyGetterMethod || mem.HasSetterMethod`.

**Comment by forki** [comment]
Ok replaces IsGetterMethod. What about IsSetterMethod?

**Comment by dungpa** [comment]
Oops, sorry. I meant:

`mem.IsGetterMethod` --> `mem.IsPropertyGetterMethod || mem.HasGetterMethod`.
`mem.IsSetterMethod` --> `mem.IsPropertySetterMethod || mem.HasSetterMethod`.

**Comment by forki** [comment]
thanks

2015-01-03 15:51 GMT+01:00 Anh-Dung Phan <notifications@github.com>:

**Pull request merged**
